import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getPb } from "@/lib/pb";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pb = getPb();
  const theme = pb.authStore.model?.ui_state?.theme ?? "light";
  return (
    <html lang="en">
      <body className={cn(inter.className, theme)}>{children}</body>
    </html>
  );
}
