import "../globals.css";
import "../data-tables-css.css";
import "../satoshi.css";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookie = cookies().get("pb_auth")?.value;
  if (cookie) return redirect("/");
  return (
    <html lang="en">
      <body className="dark grid h-screen w-screen place-items-center border  bg-black">
        <div className="dark:bg-black dark:text-bodydark">
          <div className="z-50 mx-auto  max-w-screen-2xl bg-black p-4 md:p-6 2xl:p-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
