/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/acOydZzJDNf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverTrigger,
  PopoverContent,
} from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import {
  Card,
  CardHeader,
  CardDescription,
  CardTitle,
  CardContent,
} from "@/components/ui/card";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { CalendarClockIcon } from "lucide-react";

export default async function Page() {
  return (
    <div className="flex flex-col min-h-screen w-full">
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
        <div className="flex items-center gap-4">
          <h1 className="font-semibold text-lg md:text-xl">Finances</h1>
          <div className="ml-flex items-center gap-2">
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  id="date"
                  variant="outline"
                  className="w-[280px] justify-start text-left font-normal"
                >
                  <CalendarClockIcon className="mr-2 h-4 w-4" />
                  June 01, 2023 - June 30, 2023
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="end">
                <Calendar initialFocus mode="range" numberOfMonths={2} />
              </PopoverContent>
            </Popover>
          </div>
        </div>
        <div className="grid gap-6">
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardDescription>Revenue from Bookings</CardDescription>
                <CardTitle>$120,000.00</CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Source</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>Hotel Bookings</TableCell>
                      <TableCell className="text-right">$80,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Flight Bookings</TableCell>
                      <TableCell className="text-right">$30,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Tour Packages</TableCell>
                      <TableCell className="text-right">$10,000.00</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Employee Expenses</CardDescription>
                <CardTitle>$50,000.00</CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Expense</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>Salaries</TableCell>
                      <TableCell className="text-right">$35,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Benefits</TableCell>
                      <TableCell className="text-right">$10,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Training</TableCell>
                      <TableCell className="text-right">$5,000.00</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Overview</CardDescription>
                <CardTitle>$70,000.00</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <div>Net Profit</div>
                    <div className="font-medium">$70,000.00</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>Profit Margin</div>
                    <div className="font-medium">35%</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>Operating Expenses</div>
                    <div className="font-medium">$20,000.00</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>Cash Flow</div>
                    <div className="font-medium">$50,000.00</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardDescription>Business Expenses</CardDescription>
                <CardTitle>$30,000.00</CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Expense</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>Marketing</TableCell>
                      <TableCell className="text-right">$10,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Office Rent</TableCell>
                      <TableCell className="text-right">$8,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>IT Infrastructure</TableCell>
                      <TableCell className="text-right">$5,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Travel</TableCell>
                      <TableCell className="text-right">$4,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Utilities</TableCell>
                      <TableCell className="text-right">$3,000.00</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Cash and Investments</CardDescription>
                <CardTitle>$200,000.00</CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Account</TableHead>
                      <TableHead className="text-right">Balance</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>Checking Account</TableCell>
                      <TableCell className="text-right">$50,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Savings Account</TableCell>
                      <TableCell className="text-right">$30,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Stocks</TableCell>
                      <TableCell className="text-right">$80,000.00</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Bonds</TableCell>
                      <TableCell className="text-right">$40,000.00</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Liabilities</CardDescription>
                <CardTitle>$100,000.00</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <div>Business Loan</div>
                    <div className="font-medium">$80,000.00</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>Credit Card Debt</div>
                    <div className="font-medium">$20,000.00</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
